set-option -g prefix C-b
bind-key C-b send-prefix

bind-key 0 kill-pane
bind-key 1 break-pane
bind-key 2 split-window -v -c "#{pane_current_path}"
bind-key 3 split-window -h -c "#{pane_current_path}"

set -g mouse on